### ISSUE TITLE
Brat save() method is not able to export attributes & brat conf file

### ISSUE THREAD

**Issue by Raynaudy** [equipe22/pymedext_core#2]
The save() method of the Brat dataTransform class only export annotation.type.

It could be usefull to also export attributes with appropriate conf file.

I coded a solution for that and would be happy to share it here but I don't have correct rights to publish my branch as a pull request

**Comment by aneuraz** [comment]
Hi @Raynaudy, 
Thank you for submitting this first issue ! 
It is a very good point, it would be a nice addition.
I think that you need to fork the repo and submit a pull request from your own fork.

**Comment by Raynaudy** [comment]
Yes, indeed ! 
It should be good now !
